package com.fourguard.wms.infrastructure.persistence.entity;

import com.fourguard.wms.domain.enums.SupplierScopeType;
import com.fourguard.wms.domain.enums.SupplierStatus;
import com.fourguard.wms.shared.audit.BaseVersionedEntity;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.DynamicUpdate;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity for wms.suppliers — master supplier catalog.
 *
 * <p>Design notes:
 * <ul>
 *   <li>Extends {@link BaseVersionedEntity} for optimistic locking (version column).</li>
 *   <li>1:1 relations (contact, address, commercialTerms) use CascadeType.ALL + orphanRemoval
 *       so a single save() persists all related records atomically.</li>
 *   <li>scope_type drives visibility in 3PL architecture:
 *       GLOBAL=no FK needed, CLIENT=client_id required, WAREHOUSE=branch_id required.</li>
 *   <li>supplierTypeCode is String (not enum) to allow catalog extensibility without redeploy.</li>
 *   <li>Soft delete: is_deleted=true marks archived suppliers. Physical delete is never performed.</li>
 * </ul>
 * </p>
 */
@Entity
@Table(
    name = "suppliers",
    schema = "wms",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_supplier_org_code",   columnNames = {"organization_id", "code"}),
        @UniqueConstraint(name = "uk_supplier_org_tax_id", columnNames = {"organization_id", "tax_id"})
    }
)
@DynamicUpdate
@Getter
@Setter
@NoArgsConstructor
@SuperBuilder(toBuilder = true)
public class SupplierEntity extends BaseVersionedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID id;

    // --- Owning organization ---
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "organization_id", nullable = false)
    private OrganizationEntity organization;

    /** Sequential code per organization. Format: 'PRV-0001'. Generated by SupplierService. */
    @Column(name = "code", length = 20, nullable = false)
    private String code;

    // --- Fiscal information ---
    @Column(name = "legal_name", length = 250, nullable = false)
    private String legalName;

    @Column(name = "commercial_name", length = 150)
    private String commercialName;

    /** RFC (MX) or equivalent Tax ID. Unique per organization. */
    @Column(name = "tax_id", length = 20, nullable = false)
    private String taxId;

    // --- Classification ---
    /** FK code → wms.cat_supplier_types. Stored as String for extensibility. */
    @Column(name = "supplier_type_code", length = 30, nullable = false)
    private String supplierTypeCode;

    @Column(name = "is_preferred", nullable = false)
    @Builder.Default
    private Boolean isPreferred = false;

    // --- Operational status ---
    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    @Builder.Default
    private SupplierStatus status = SupplierStatus.ACTIVE;

    /** Mandatory when status is INACTIVE or BLOCKED. */
    @Column(name = "status_reason", length = 500)
    private String statusReason;

    @Column(name = "status_changed_at")
    private OffsetDateTime statusChangedAt;

    @Column(name = "status_changed_by", length = 100)
    private String statusChangedBy;

    // --- 3PL Scope ---
    @Enumerated(EnumType.STRING)
    @Column(name = "scope_type", length = 15, nullable = false)
    @Builder.Default
    private SupplierScopeType scopeType = SupplierScopeType.GLOBAL;

    /** Required when scopeType = CLIENT. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    private ClientEntity client;

    /**
     * Required when scopeType = WAREHOUSE.
     * Maps to wms.branches (no "warehouses" table exists).
     * Exposed as 'warehouseId' in FE DTOs for compatibility.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "branch_id")
    private BranchEntity branch;

    // --- Notes ---
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    // --- 1:1 Relations (cascaded) ---
    @OneToOne(mappedBy = "supplier", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private SupplierContactEntity contact;

    @OneToOne(mappedBy = "supplier", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private SupplierAddressEntity address;

    @OneToOne(mappedBy = "supplier", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private SupplierCommercialTermsEntity commercialTerms;

    // --- Soft delete ---
    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private Boolean isActive = true;

    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private Boolean isDeleted = false;

    @Column(name = "deleted_at")
    private OffsetDateTime deletedAt;

    @Column(name = "deleted_by", length = 100)
    private String deletedBy;

    // --- Helper: bind bidirectional 1:1 back-references ---
    public void setContact(SupplierContactEntity contact) {
        this.contact = contact;
        if (contact != null) contact.setSupplier(this);
    }

    public void setAddress(SupplierAddressEntity address) {
        this.address = address;
        if (address != null) address.setSupplier(this);
    }

    public void setCommercialTerms(SupplierCommercialTermsEntity commercialTerms) {
        this.commercialTerms = commercialTerms;
        if (commercialTerms != null) commercialTerms.setSupplier(this);
    }
}
